# Generated by Django 5.0.3 on 2024-03-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_creacion',
        ),
    ]
